# Generated by Django 5.1.1 on 2024-10-05 15:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('c2c', 'C2C'), ('sbp', 'SBP')], max_length=4, verbose_name='Тип')),
                ('payment_details', models.CharField(max_length=255, verbose_name='Реквизиты')),
                ('client_bank', models.IntegerField(blank=True, null=True, verbose_name='Банк клиента для перевода')),
                ('user_bank', models.CharField(max_length=255, verbose_name='Банк отправителя средств')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('manual', 'Manual')], default='new', max_length=10, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма (в руб.)')),
                ('net_amount_in_usdt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма начисленная юзеру')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('taken_time', models.DateTimeField(blank=True, null=True, verbose_name='Время взятия')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('receipt_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на чек')),
                ('merchant_id', models.IntegerField(verbose_name='ID Мерчанта')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ID Юзера')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Покупатель')),
                ('problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Проблема')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'Заявки',
                'indexes': [models.Index(fields=['status'], name='database_ap_status_6fddf7_idx'), models.Index(fields=['type'], name='database_ap_type_e2c26f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Процент начисления')),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Заработок')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заявки')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Максимальная сумма заявки')),
                ('active', models.BooleanField(default=True, verbose_name='Возможность обрабатывать заявки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('execution_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения запроса')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма запроса (в USDT)')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=10, verbose_name='Статус запроса')),
                ('transaction_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш транзакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на вывод',
                'verbose_name_plural': 'Запросы на вывод',
            },
        ),
    ]
