# Generated by Django 5.1.1 on 2024-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_application_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_bank',
            field=models.CharField(blank=True, null=True, verbose_name='Банк клиента для перевода'),
        ),
    ]
