# Generated by Django 5.1.1 on 2024-10-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_user_bank_application_from_bank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('edit_note_and_status', 'Can edit note and status')], 'verbose_name': 'заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'permissions': [('edit_processing_withdrawal', 'Can edit processing withdrawal')], 'verbose_name': 'Запрос на вывод', 'verbose_name_plural': 'Запросы на вывод'},
        ),
    ]
