# Generated by Django 5.1.1 on 2024-10-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('edit_note_and_status', 'Права для саппорта (заметка и статус)')], 'verbose_name': 'заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'permissions': [('edit_processing_withdrawal', 'Права для саппорта (статус и хэш)')], 'verbose_name': 'Запрос на вывод', 'verbose_name_plural': 'Запросы на вывод'},
        ),
    ]
