# Generated by Django 5.1.1 on 2024-10-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_application__user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='from_bank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк отправителя средств'),
        ),
        migrations.AlterField(
            model_name='application',
            name='to_bank',
            field=models.CharField(default=1, verbose_name='Банк клиента для перевода'),
            preserve_default=False,
        ),
    ]
