# Generated by Django 5.1.1 on 2024-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_application_from_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='processing', max_length=10, verbose_name='Статус запроса'),
        ),
    ]
