# Generated by Django 5.1.1 on 2024-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название поля'),
        ),
    ]
