# Generated by Django 5.1.1 on 2024-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_adminactionlog_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactionlog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='adminactionlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='adminactionlog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='changes',
            field=models.TextField(blank=True, null=True, verbose_name='Изменения'),
        ),
    ]
