# Generated by Django 5.1.1 on 2024-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_adminactionlog_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='closing_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Курс на момент исполнения заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент начисления'),
        ),
        migrations.AddField(
            model_name='application',
            name='rate_after_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Курс за вычетом комиссии'),
        ),
    ]
