# Generated by Django 5.1.1 on 2024-10-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'permissions': [('can_view_all_reports', 'Может получить отчёт со всеми данными всех пользователей')], 'verbose_name': 'Запрошенный отчёт', 'verbose_name_plural': 'Запрошенные отчёты'},
        ),
    ]
