# Generated by Django 5.1.1 on 2024-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_userprofile_problems_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='merchant_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Баланс мерчанта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='merchant_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Лимит мерчанта'),
        ),
    ]
