# Generated by Django 5.1.1 on 2024-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_userprofile_merchant_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='merchant_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Процент списания у мерчанта'),
        ),
    ]
