# Generated by Django 5.1.1 on 2024-10-26 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_userprofile_merchant_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='Мерчант'),
        ),
        migrations.AddField(
            model_name='application',
            name='merchant_rate_after_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс за вычетом комиссии для мерчанта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rate_after_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Курс за вычетом комиссии для команд'),
        ),
    ]
