# Generated by Django 5.1.1 on 2024-10-26 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_application__merchant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='_merchant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='_user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_id',
        ),
        migrations.AddField(
            model_name='application',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_applications', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='application',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='Мерчант'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.OneToOneField(db_column='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
