# Generated by Django 5.1.1 on 2024-11-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_application__merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recipients_bank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк для перевода'),
        ),
    ]
